### PR TITLE
Add partial stb_truetype

### PR DESCRIPTION
**Pull request by kevinresol**
Not experienced in cpp, please review to see if there are any memory problems in my code.

for now only a few functions are implemented, focusing on bitmap generation:
- bake_font_bitmap
- pack_begin
- pack_font_range
- pack_font_ranges
- pack_end

other functions will be added in another PR

### CODE REVIEW

**Comment by ruby0x1** [comment]
Sorry for the delay. 
Most of the cpp looks fine.

Quick questions:
- Why does the test reference `-lib format`?

Also could you squash the commits down into one commit please? If you're not sure how to best go about that let me know.

**Comment by kevinresol** [comment]
Done!

**Comment by kevinresol** [comment]
@underscorediscovery I think in the beginning I used the format lib to write out the png's. Already removed now.

**Comment by ruby0x1** [comment]
We should try to have more coverage of the API's that are included, like rect_pack and the other true_type ones at some point too. In future PR from a branch let's you move on master without it getting caught up in the PR :)

For now it looks good, thanks!

**Comment by ruby0x1** [comment]
Also @kevinresol just to be sure, the font file should probably come with it's license - and if the license is not applicable we must find another. Can you look at that sometime please?

**Comment by ruby0x1** [comment]
Nevermind, I'll sort out the font stuff because the test is referencing `c:/windows`.... I missed that but it really should be isolated and cross platform (as is the point here :))

**Pull request merged**
